### ISSUE TITLE
Persist squad recommendations until another click event?

### ISSUE THREAD

**Issue by alttext** [genskaar/tb_empire#12]
It would be nice if the squads would show - sometimes I want to copy text and other times I want to see which toon it is (by looking at the image name). I looked into doing this with vue.js but my javascript chops are not strong.

**Comment by genskaar** [comment]
Hi there,

Yes, I've thought about this before when I wanted to add video links to missions. I couldn't find a good way of doing this at the time which didn't create windows that blocked other mission nodes.

My solution to this before was to prototype a [discord bot version of the map](https://genskaar.github.io/tb_geo/media/screenshots/ss1.png) which worked ok, but now there are far better bots for rote :)

If you do manage to get something working, please by all means create a pull request and I'll take a look

**Comment by alttext** [comment]
I got something working here that works on desktop but has some issues on
mobile.

https://alttext.github.io/tb_empire/html/felucia.html

You can tap the battle icon again to dismiss the squad screen.

I've made, what I believe are some UI improvements in this version but I am
totally fine NOT having my own branch if you would like me to attempt to
make merge requests into your repo.
